export const cardActionTypes = {
	CREATE_CARD: 'CREATE_CARD',
	EDIT_CARD: 'EDIT_CARD',
	REMOVE_CARD: 'REMOVE_CARD',
	CREATE_LABEL: 'CREATE_LABEL',
	REMOVE_LABEL: 'REMOVE_LABEL',
	CREATE_TASK: 'CREATE_TASK',
	REMOVE_TASK: 'REMOVE_TASK',
	MARK_ALL_TASKS_AS: 'MARK_ALL_TASKS_AS',
	REMOVE_COMPLETE_TASKS: 'REMOVE_COMPLETE_TASKS',
	CHANGE_TASK_STATE: 'CHANGE_TASK_STATE',
};